### ISSUE TITLE
UnhandledPromiseRejectionWarning (again -> https://github.com/synox/void-mail/issues/9)

### ISSUE THREAD

**Issue by erm3nda** [synox/void-mail#13]
Im getting again some problems like what i had in https://github.com/synox/void-mail/issues/9

This is the current output.

```
    # pm2 logs 0
[TAILING] Tailing last 15 lines for [0] process (change the value with --lines option)
/root/.pm2/logs/email-out.log last 15 lines:
0|email    | 
0|email    | > void-mail@0.0.0 start /root/email
0|email    | > node ./app.js
0|email    | 

/root/.pm2/logs/email-error.log last 15 lines:
0|email    | (node:30300) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
0|email    |     at MailRepository.add (/root/email/domain/mail-repository.js:22:29)
0|email    |     at mail.to.forEach.to (/root/email/application/mail-processing-service.js:56:24)
0|email    |     at Array.forEach (<anonymous>)
0|email    |     at MailProcessingService.onNewMail (/root/email/application/mail-processing-service.js:55:11)
0|email    |     at ImapService.imapService.on.mail (/root/email/app.js:28:24)
0|email    |     at ImapService.emit (events.js:198:13)
0|email    |     at mails.forEach.mail (/root/email/application/imap-service.js:222:11)
0|email    |     at Array.forEach (<anonymous>)
0|email    |     at ImapService._getMailHeadersAndEmitAsEvents (/root/email/application/imap-service.js:218:10)
0|email    |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|email    | (node:30300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
0|email    | (node:30300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by erm3nda** [comment]
Still getting the same problem. Also, i've noticed that emails are not being displayed. I've double checked that emails comes to mailbox.

Regards.

```
0|email    | (node:30300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
0|email    | (node:30300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
0|email    | (node:16265) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
0|email    |     at MailRepository.add (/root/email/domain/mail-repository.js:22:29)
0|email    |     at mail.to.forEach.to (/root/email/application/mail-processing-service.js:56:24)
0|email    |     at Array.forEach (<anonymous>)
0|email    |     at MailProcessingService.onNewMail (/root/email/application/mail-processing-service.js:55:11)
0|email    |     at ImapService.imapService.on.mail (/root/email/app.js:28:24)
0|email    |     at ImapService.emit (events.js:198:13)
0|email    |     at mails.forEach.mail (/root/email/application/imap-service.js:222:11)
0|email    |     at Array.forEach (<anonymous>)
0|email    |     at ImapService._getMailHeadersAndEmitAsEvents (/root/email/application/imap-service.js:218:10)
0|email    |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|email    | (node:16265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
0|email    | (node:16265) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by erm3nda** [comment]
3 months and not reply. Closing the issue and forgetting it.
Regards.
